SELECT 
    NVL(t1.RULE_ID, t2.RULE_ID) AS RULE_ID,
    t1.RULE_NAME AS MAIN_RULE_NAME,
    t2.RULE_NAME AS BK_RULE_NAME,
    t1.RULE_DESCRIPTION AS MAIN_RULE_DESCRIPTION,
    t2.RULE_DESCRIPTION AS BK_RULE_DESCRIPTION,
    CASE 
        WHEN t1.RULE_ID IS NULL THEN 'EXISTS ONLY IN BK'
        WHEN t2.RULE_ID IS NULL THEN 'EXISTS ONLY IN MAIN'
        WHEN LTRIM(RTRIM(t1.RULE_NAME)) <> LTRIM(RTRIM(t2.RULE_NAME)) 
          OR LTRIM(RTRIM(t1.RULE_DESCRIPTION)) <> LTRIM(RTRIM(t2.RULE_DESCRIPTION)) 
          THEN 'DIFFERENT'
        ELSE 'IDENTICAL'
    END AS DIFF_FLAG
FROM 
    xxmro.MROI_OTL_TOD_AWS_RULES t1
FULL OUTER JOIN 
    xxmro.MROI_OTL_TOD_AWS_RULES_BK t2 ON t1.RULE_ID = t2.RULE_ID
WHERE 
    t1.RULE_ID IS NULL 
    OR t2.RULE_ID IS NULL 
    OR LTRIM(RTRIM(t1.RULE_NAME)) <> LTRIM(RTRIM(t2.RULE_NAME))
    OR LTRIM(RTRIM(t1.RULE_DESCRIPTION)) <> LTRIM(RTRIM(t2.RULE_DESCRIPTION));